# render.yaml

services:
  - type: web
    name: ten-web-service-cua-ban # Ví dụ: ahp-app
    env: python
    plan: free # Hoặc plan của bạn
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      # --- Phần quan trọng cho DATABASE_URL ---
      - key: DATABASE_URL   # Tên biến môi trường mà code app.py của bạn sẽ đọc
        fromDatabase:
          name: test_2s9p # <<<--- TÊN NÀY QUAN TRỌNG
          property: connectionString            # Chỉ định lấy chuỗi kết nối
      # ------------------------------------------

      - key: SECRET_KEY    # Render tự tạo khóa bí mật
        generateValue: true
      - key: PYTHON_VERSION # Tùy chọn: chỉ định phiên bản Python
        value: 3.11 # Ví dụ


databases:
  - name: test_2s9p # <<<--- TÊN DATABASE CỦA BẠN
    plan: free # Hoặc plan của bạn
